environment:
  nodejs_version: "6.8.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node platform
  - node --version
  - npm --version
  - npm test

build: off